services:
  sotu-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: presidential-speech-dashboard
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - TAIPY_PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
